parameters:
  - name: repoUrl
    type: string
    default: 'https://gitlab.com/nanuchi/docker-in-1-hour.git'

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CloneAndBuild
    displayName: 'Clone Repository and Execute Tasks'
    jobs:
      - job: CloneAndExecute
        steps:
          - script: echo "Cloning repository from ${{ parameters.repoUrl }}"
            displayName: 'Display Repo URL'
          
          - script: |
              git clone ${{ parameters.repoUrl }} repo
              cd repo
              echo "Add other tasks to build, test, and deploy your project."
              # Here you can add other git commands or any build/test/deploy scripts
            displayName: 'Clone repository and execute tasks'

  - stage: EchoStage
    displayName: 'Additional Echo Scripts'
    jobs:
      - job: EchoJob
        steps:
          - script: echo "This is the first echo statement in the new stage."
            displayName: 'Echo Script 1'

          - script: echo "This is the second echo statement in the new stage."
            displayName: 'Echo Script 2'

  - stage: DockerBuildAndPush
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: DockerJob
        steps:
          - script: |
              echo "Logging in to Docker Hub"
              docker login --username kiranqot --password t3yL:JDjmTXKV4e
            displayName: 'Docker Login'
          
          - script: |
              echo "Building Docker image"
              git clone ${{ parameters.repoUrl }} repo2
              cd repo2
              docker build -t kiranqot/azuretest:latest .
            displayName: 'Build Docker Image'

          - script: |
              echo "Pushing Docker image to Docker Hub"
              docker push kiranqot/azuretest:latest
            displayName: 'Push Docker Image to Docker Hub'

          - script: |
              echo "Docker image pushed successfully."
            displayName: 'Echo Success'


  - stage: DockerRun
    displayName: 'Install Docker and Run Container'
    jobs:
      - job: DockerJob
        steps:
          - script: |
              echo "Running in Docker"
              docker login --username kiranqot --password t3yL:JDjmTXKV4e
            displayName: 'Running Docker Container'
        # steps:
        # - task: DockerInstaller@0
        #   inputs:
        #     dockerVersion: '17.09.0-ce'